# Copyright 2026 3LC Inc.
# SPDX-License-Identifier: Apache-2.0
r"""Shared UI component for data-source inputs (files and folders on the compute node).

Generates the HTML + JS block that plugins embed in their UI fragments.
This ensures a consistent file/folder selection experience across every plugin
that needs to reference data on the compute node — local paths, S3 URLs, or
browser-uploaded files all resolve to a compute-visible location.

Usage in a plugin's ``get_ui_fragment()``::

    from tlc_plugin_sdk.shared.data_source_ui import data_source_ui_script
    from tlc_plugin_sdk.shared.ui_inject import inject_scripts

    raw = Path("ui.html").read_text()
    html = inject_scripts(raw, data_source_ui_script())

Then in the plugin's ``ui.html`` JavaScript:

.. code-block:: javascript

    // Render a data-source input
    var html = _tlcDataSourceHtml('my-field', {
        placeholder: 'Path to dataset YAML...',
        accept: '*.yaml,*.yml',      // glob filter for the browser
        allowUpload: false,           // show upload toggle?
        mode: 'file',                 // 'file' or 'folder'
        purpose: 'input',             // 'input' (default) or 'output'
    });
    container.innerHTML = html;

    // Bind the browse/upload handlers (call AFTER inserting into DOM)
    _tlcBindDataSource('my-field', computeUrl, pluginId);

    // Read the value at submit time
    var path = _tlcGetDataSourceValue('my-field');

The widget requires the plugin to serve the ``/browse`` and (optionally)
``/upload-temp`` routes from :mod:`~tlc_plugin_sdk.shared.data_source_routes`.

Browsing is not only the compute's own disk: the panel's location bar lists every
bucket the compute service knows (its generic ``/api/infra/storage`` surface, the same
locations as the Hub's Storage page), and browsing one of them goes through the
provider's ``/list`` route. Picking a bucket folder writes its URL (``s3://…``) into the
field, which plugins already accept. Volumes and node disks are not offered here: a
plugin running on the controller cannot read them. Without an infrastructure plugin
(or on a host without that surface) the bar shows only "This compute", as before.
"""

from __future__ import annotations

# fmt: off
DATA_SOURCE_UI_JS = (
    "// -- Shared Data Source UI ------\n"
    "(function(){\n"
    "var st=document.createElement('style');st.textContent=\n"
    "'.tlc-ds-wrapper{position:relative}'"
    "+'.tlc-ds-browse-panel{position:absolute;left:0;right:0;z-index:100;'"
    "+' border:1px solid var(--border);border-radius:6px;'"
    "+' margin-top:4px;max-height:320px;overflow-y:auto;background:var(--bg-card);'"
    "+' font-size:12px;display:none;'"
    "+' box-shadow:0 4px 16px rgba(0,0,0,.12)}'"
    "+'.tlc-ds-browse-panel.open{display:block}'"
    "+'.tlc-ds-breadcrumb{display:flex;align-items:center;gap:2px;padding:8px 10px;'"
    "+' border-bottom:1px solid var(--border);font-size:11px;flex-wrap:wrap;'"
    "+' background:var(--bg-secondary,rgba(0,0,0,.02))}'"
    "+'.tlc-ds-breadcrumb span{cursor:pointer;color:var(--accent);font-weight:500}'"
    "+'.tlc-ds-breadcrumb span:hover{text-decoration:underline}'"
    "+'.tlc-ds-breadcrumb .sep{color:var(--text-muted);cursor:default;margin:0 1px}'"
    "+'.tlc-ds-breadcrumb .sep:hover{text-decoration:none}'"
    "+'.tlc-ds-filter-note{padding:4px 10px;font-size:10px;color:var(--text-muted);'"
    "+' border-bottom:1px solid var(--border-light,rgba(0,0,0,.04))}'"
    "+'.tlc-ds-entry{display:flex;align-items:center;gap:8px;padding:5px 10px;'"
    "+' cursor:pointer;border-bottom:1px solid var(--border-light,rgba(0,0,0,.04))}'"
    "+'.tlc-ds-entry:hover{background:var(--golden-light,rgba(217,119,6,.06))}'"
    "+'.tlc-ds-entry:last-child{border-bottom:none}'"
    # Folders the compute process can't open (e.g. macOS TCC-protected packages):
    # dimmed, no pointer, and the golden hover is suppressed so they don't invite a click.
    "+'.tlc-ds-entry-disabled{cursor:default;opacity:.5}'"
    "+'.tlc-ds-entry-disabled:hover{background:transparent}'"
    "+'.tlc-ds-entry .ds-icon{flex-shrink:0;width:16px;text-align:center;font-size:13px}'"
    "+'.tlc-ds-entry .ds-name{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'"
    "+'.tlc-ds-entry .ds-size{font-size:10px;color:var(--text-muted);flex-shrink:0}'"
    # Scoped to the panel (not .tlc-ds-entry): the folder-mode select button renders in
    # the BREADCRUMB — entry-scoped rules left it a naked native <button>.
    "+'.tlc-ds-browse-panel .ds-select-btn{font-size:10px;padding:2px 8px;border:1px solid var(--border);'"
    "+' border-radius:3px;background:var(--bg-card);cursor:pointer;color:var(--accent);font-weight:600;flex-shrink:0}'"
    "+'.tlc-ds-browse-panel .ds-select-btn:hover{background:var(--accent);color:#fff;border-color:var(--accent)}'"
    "+'.tlc-ds-empty{padding:16px;text-align:center;color:var(--text-muted);font-size:11px}'"
    "+'.tlc-ds-error{padding:10px;color:var(--error,#ef4444);font-size:11px}'"
    "+'.tlc-ds-upload-zone{position:absolute;left:0;right:0;z-index:100;'"
    "+' border:2px dashed var(--border);border-radius:6px;padding:20px;'"
    "+' text-align:center;cursor:pointer;transition:border-color .15s,background .15s;'"
    "+' margin-top:4px;display:none;font-size:12px;background:var(--bg-card);'"
    "+' box-shadow:0 4px 16px rgba(0,0,0,.12)}'"
    "+'.tlc-ds-upload-zone.open{display:block}'"
    "+'.tlc-ds-upload-zone:hover{border-color:var(--accent);background:var(--accent-light,rgba(42,74,97,.04))}'"
    "+'.tlc-ds-upload-zone.dragging{border-color:var(--accent);background:var(--accent-light,rgba(42,74,97,.08))}'"
    "+'.tlc-ds-upload-info{font-size:11px;color:var(--text-muted);margin-top:4px;display:none}'"
    "+'.tlc-ds-actions{display:flex;gap:6px;align-items:center}'"
    "+'.tlc-ds-loc{display:flex;align-items:center;gap:8px;padding:6px 10px;'"
    "+' border-bottom:1px solid var(--border);background:var(--bg-card);font-size:11px}'"
    "+'.tlc-ds-loc label{color:var(--text-muted);white-space:nowrap}'"
    "+'.tlc-ds-loc select{flex:1;min-width:0;font:inherit;font-size:11.5px;padding:3px 6px;'"
    "+' border:1px solid var(--border);border-radius:4px;background:var(--bg);color:var(--text)}';\n"
    "document.head.appendChild(st)})();\n"
    "\n"
    "function _tlcDataSourceHtml(idPrefix, config) {\n"
    "  config = config || {};\n"
    "  var ph = config.placeholder || 'Path on compute node or URL…';\n"
    "  var allowUpload = config.allowUpload || false;\n"
    "  var accept = config.accept || '';\n"
    "  var h = '';\n"
    "  h += '<div class=\"tlc-ds-wrapper\">';\n"
    "  h += '<div class=\"tlc-ds-actions\">';\n"
    "  h += '<input type=\"text\" id=\"' + idPrefix + '\" class=\"form-control\"';\n"
    "  h += ' placeholder=\"' + ph + '\" style=\"flex:1\">';\n"
    "  h += '<button type=\"button\" class=\"btn btn-secondary btn-sm\" id=\"' + idPrefix + '-ds-browse-btn\"';\n"
    "  h += ' style=\"white-space:nowrap\">Browse…</button>';\n"
    "  if (allowUpload) {\n"
    "    h += '<button type=\"button\" class=\"btn btn-secondary btn-sm\" id=\"' + idPrefix + '-ds-upload-btn\"';\n"
    "    h += ' style=\"white-space:nowrap\">Upload</button>';\n"
    "  }\n"
    "  h += '</div>';\n"
    "  // Browse panel (inline, hidden by default)\n"
    "  h += '<div class=\"tlc-ds-browse-panel\" id=\"' + idPrefix + '-ds-panel\"></div>';\n"
    "  // Upload zone (hidden by default)\n"
    "  if (allowUpload) {\n"
    "    var acceptAttr = accept ? accept.split(',').map(function(g){"
    " return g.trim().replace('*',''); }).join(',') : '';\n"
    "    h += '<div class=\"tlc-ds-upload-zone\" id=\"' + idPrefix + '-ds-upload-zone\">';\n"
    "    h += '<div style=\"font-weight:600;margin-bottom:4px\">Drop file here</div>';\n"
    "    h += '<div style=\"color:var(--text-muted)\">or click to browse';\n"
    "    if (accept) h += ' — ' + accept;\n"
    "    h += '</div>';\n"
    "    h += '<input type=\"file\" id=\"' + idPrefix + '-ds-file-input\"';\n"
    "    if (acceptAttr) h += ' accept=\"' + acceptAttr + '\"';\n"
    "    h += ' style=\"display:none\">';\n"
    "    h += '</div>';\n"
    "    h += '<div class=\"tlc-ds-upload-info\" id=\"' + idPrefix + '-ds-upload-info\"></div>';\n"
    "  }\n"
    "  h += '</div>';  // close .tlc-ds-wrapper\n"
    "  return h;\n"
    "}\n"
    "\n"
    "function _tlcBindDataSource(idPrefix, computeUrl, pluginId, config) {\n"
    "  config = config || {};\n"
    "  var glob = config.accept || '';\n"
    "  var mode = config.mode || 'file';\n"
    "  var purpose = config.purpose || 'input';\n"
    "  var input = document.getElementById(idPrefix);\n"
    "  var browseBtn = document.getElementById(idPrefix + '-ds-browse-btn');\n"
    "  var panel = document.getElementById(idPrefix + '-ds-panel');\n"
    "  var uploadBtn = document.getElementById(idPrefix + '-ds-upload-btn');\n"
    "  var uploadZone = document.getElementById(idPrefix + '-ds-upload-zone');\n"
    "  var API = window.PLUGIN_API;\n"
    "\n"
    "  // Format file sizes\n"
    "  function _fmtSize(bytes) {\n"
    "    if (bytes == null) return '';\n"
    "    if (bytes < 1024) return bytes + ' B';\n"
    "    if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';\n"
    "    return (bytes / 1048576).toFixed(1) + ' MB';\n"
    "  }\n"
    "\n"
    "  function _esc(s) {\n"
    "    if (!s) return '';\n"
    "    var d = document.createElement('div');\n"
    "    d.textContent = s;\n"
    "    return d.innerHTML;\n"
    "  }\n"
    "\n"
    "  // Locations: this compute's disk, plus every bucket the compute service lists (the Hub's\n"
    "  // Storage page shows the same). Fetched once per page and shared by every field on it.\n"
    "  var _loc = { kind: 'local' };\n"
    "  function _locations() {\n"
    "    var cache = window._tlcDsLocations;\n"
    "    if (cache && (Date.now() - cache.at) < 60000) return Promise.resolve(cache.list);\n"
    "    return API.authFetch(computeUrl + '/api/infra/storage')\n"
    "      .then(function(r) { return r.ok ? r.json() : { storage: [], providers: [] }; })\n"
    "      .then(function(out) {\n"
    "        var byPlugin = {};\n"
    "        (out.providers || []).forEach(function(p) { byPlugin[p.plugin_id] = p; });\n"
    "        var list = (out.storage || []).filter(function(s) {\n"
    "          // Only bucket URLs: a plugin on the controller reads s3://-style URLs, not volumes or node disks.\n"
    "          return s.kind === 'bucket' && s.url && (byPlugin[s.plugin_id] || {}).browse;\n"
    "        }).map(function(s) {\n"
    "          return { kind: 'bucket', plugin_id: s.plugin_id, url: String(s.url).replace(/\\/$/, ''),\n"
    "                   name: s.name || s.id, label: (byPlugin[s.plugin_id] || {}).label || 'bucket', root: "
    "!!s.project_root };\n"
    "        });\n"
    "        window._tlcDsLocations = { at: Date.now(), list: list };\n"
    "        return list;\n"
    "      })\n"
    "      .catch(function() { return []; });\n"
    "  }\n"
    "  function _locationFor(value) {\n"
    "    // A value inside a known bucket opens that bucket; anything else is this compute.\n"
    "    var list = (window._tlcDsLocations || {}).list || [];\n"
    "    for (var i = 0; i < list.length; i++) { if (value === list[i].url || value.indexOf(list[i].url + '/') === 0) "
    "return list[i]; }\n"
    "    return { kind: 'local' };\n"
    "  }\n"
    "  function _globToRegex(pattern) {\n"
    "    var parts = pattern.split(',').map(function(g) { return g.trim(); }).filter(Boolean);\n"
    "    if (!parts.length) return null;\n"
    "    return new RegExp('^(?:' + parts.map(function(g) {\n"
    "      return g.replace(/[.+^${}()|[\\]\\\\]/g, '\\\\$&').replace(/\\*/g, '.*').replace(/\\?/g, '.');\n"
    "    }).join('|') + ')$', 'i');\n"
    "  }\n"
    "\n"
    "  // Browse panel\n"
    "  var _panelOpen = false;\n"
    "  browseBtn.addEventListener('click', function() {\n"
    "    _panelOpen = !_panelOpen;\n"
    "    panel.classList.toggle('open', _panelOpen);\n"
    "    if (uploadZone) { uploadZone.classList.remove('open'); }\n"
    "    if (!_panelOpen) return;\n"
    "    panel.innerHTML = '<div class=\"tlc-ds-empty\">Loading…</div>';\n"
    "    _locations().then(function() {\n"
    "      var startPath = input.value.trim() || '~';\n"
    "      _loc = _locationFor(startPath);\n"
    "      if (_loc.kind === 'bucket') {\n"
    "        // A file URL browses its folder; a folder URL browses itself.\n"
    "        if (mode === 'file' || /\\.[A-Za-z0-9]{1,6}$/.test(startPath)) startPath = "
    "startPath.replace(/\\/[^/]*$/, '');\n"
    "        if (startPath.indexOf(_loc.url) !== 0) startPath = _loc.url;\n"
    "      } else if (startPath !== '~' && startPath.indexOf('://') === -1) {\n"
    "        // If the current value is a file path, browse its parent directory\n"
    "        var lastSlash = startPath.lastIndexOf('/');\n"
    "        if (lastSlash > 0) startPath = startPath.substring(0, lastSlash);\n"
    "      } else if (startPath.indexOf('://') !== -1) {\n"
    "        startPath = '~';  // a URL outside every known bucket: nothing here can list it\n"
    "      }\n"
    "      _browseTo(startPath);\n"
    "    });\n"
    "  });\n"
    "\n"
    "  function _browseTo(dirPath) {\n"
    "    panel.innerHTML = '<div class=\"tlc-ds-empty\">Loading…</div>';\n"
    "    if (_loc.kind === 'bucket') { _browseBucket(dirPath); return; }\n"
    "    var url = computeUrl + '/api/plugins/' + pluginId + '/browse?path=' + encodeURIComponent(dirPath);\n"
    "    if (glob) url += '&glob=' + encodeURIComponent(glob);\n"
    "    url += '&purpose=' + encodeURIComponent(purpose);\n"
    "    API.authFetch(url)\n"
    "      .then(function(r) { return r.json(); })\n"
    "      .then(function(data) {\n"
    "        if (data.error) {\n"
    "          panel.innerHTML = '<div class=\"tlc-ds-error\">' + _esc(data.error) + '</div>';\n"
    "          return;\n"
    "        }\n"
    "        _renderBrowse(data);\n"
    "      })\n"
    "      .catch(function(err) {\n"
    "        panel.innerHTML = '<div class=\"tlc-ds-error\">Failed to browse: ' + _esc(String(err)) + '</div>';\n"
    "      });\n"
    "  }\n"
    "\n"
    "  // One level of a bucket, through its provider, shaped like the local listing so one renderer serves both.\n"
    "  function _browseBucket(prefixUrl) {\n"
    "    var at = prefixUrl.replace(/\\/$/, '');\n"
    "    var url = computeUrl + '/api/infra/storage/' + encodeURIComponent(_loc.plugin_id) + '/list?url=' + "
    "encodeURIComponent(at + '/');\n"
    "    var re = glob ? _globToRegex(glob) : null;\n"
    "    API.authFetch(url)\n"
    "      .then(function(r) { return r.json().then(function(j) { if (!r.ok) throw new Error(j.detail || ('HTTP ' + "
    "r.status)); return j; }); })\n"
    "      .then(function(out) {\n"
    "        var entries = (out.prefixes || []).map(function(p) { return { name: p.name, type: 'dir', url: "
    "String(p.url).replace(/\\/$/, '') }; })\n"
    "          .concat((out.objects || []).filter(function(o) { return !re || re.test(o.name); })\n"
    "            .map(function(o) { return { name: o.name, type: 'file', size: o.size, url: o.url }; }));\n"
    "        var parent = at === _loc.url ? null : at.replace(/\\/[^/]*$/, '');\n"
    "        _renderBrowse({ path: at, root: _loc.url, parent: parent, entries: entries, truncated: !!out.truncated "
    "});\n"
    "      })\n"
    "      .catch(function(err) {\n"
    "        panel.innerHTML = '<div class=\"tlc-ds-error\">Could not read this folder: ' + _esc(String(err.message "
    "|| err)) + '</div>';\n"
    "      });\n"
    "  }\n"
    "\n"
    "  function _renderBrowse(data) {\n"
    "    var h = '';\n"
    "    // Location bar: this compute, or one of the buckets the compute service lists.\n"
    "    var locs = (window._tlcDsLocations || {}).list || [];\n"
    "    if (locs.length) {\n"
    "      h += '<div class=\"tlc-ds-loc\"><label>Location</label><select data-ds-loc>';\n"
    "      h += '<option value=\"local\"' + (_loc.kind === 'local' ? ' selected' : '') + '>This compute</option>';\n"
    "      locs.forEach(function(l, i) {\n"
    "        h += '<option value=\"' + i + '\"' + (_loc.kind === 'bucket' && _loc.url === l.url ? ' selected' : '') + "
    "'>'\n"
    "           + _esc(l.label + ' · ' + l.name + (l.root ? ' (project root)' : '')) + '</option>';\n"
    "      });\n"
    "      h += '</select></div>';\n"
    "    }\n"
    "    // Breadcrumb — anchored at the confinement root: segments above it are not\n"
    "    // places this picker can go, so they aren't rendered at all. The root shows\n"
    "    // as its basename; only the path below it gets '/'-separated segments.\n"
    "    var rootPath = data.root || '/';\n"
    "    var isUrl = rootPath.indexOf('://') !== -1;\n"
    "    h += '<div class=\"tlc-ds-breadcrumb\">';\n"
    "    var rel, base;\n"
    "    if (isUrl) {\n"
    "      h += '<span data-ds-nav=\"' + _esc(rootPath) + '\">' + _esc(_loc.name || rootPath) + '</span>';\n"
    "      rel = data.path.slice(rootPath.length).split('/').filter(Boolean);\n"
    "      base = rootPath;\n"
    "    } else if (rootPath === '/') {\n"
    "      h += '<span data-ds-nav=\"/\">/</span>';\n"
    "      rel = data.path.split('/').filter(Boolean);\n"
    "      base = '';\n"
    "    } else {\n"
    "      var rootLabel = rootPath.split('/').filter(Boolean).pop() || '/';\n"
    "      h += '<span data-ds-nav=\"' + _esc(rootPath) + '\">' + _esc(rootLabel) + '</span>';\n"
    "      rel = data.path.slice(rootPath.length).split('/').filter(Boolean);\n"
    "      base = rootPath;\n"
    "    }\n"
    "    for (var i = 0; i < rel.length; i++) {\n"
    "      h += '<span class=\"sep\">/</span>';\n"
    "      base = base + '/' + rel[i];\n"
    "      h += '<span data-ds-nav=\"' + _esc(base) + '\">' + _esc(rel[i]) + '</span>';\n"
    "    }\n"
    "    // Select-folder button (for mode='folder'). In output mode, a current\n"
    "    // directory that isn't writable can't receive a save, so disable the button.\n"
    "    if (mode === 'folder') {\n"
    "      var folderUnwritable = (purpose === 'output' && data.writable === false);\n"
    "      h += '<button type=\"button\" class=\"ds-select-btn\" data-ds-select-folder=\"' + _esc(data.path) + '\"'"
    "         + (folderUnwritable ? ' disabled title=\"Not writable — you may not be able to save here\"' : '')"
    "         + ' style=\"margin-left:auto\">Select This Folder</button>';\n"
    "    }\n"
    "    h += '</div>';\n"
    "    // Filter note — only files are glob-filtered server-side (see data_source_routes.py);\n"
    "    // folders always show regardless of the pattern, so this caption is about what's\n"
    "    // selectable here, not what's listed.\n"
    "    if (glob) {\n"
    "      h += '<div class=\"tlc-ds-filter-note\">Showing files matching: ' + _esc(glob) + '</div>';\n"
    "    }\n"
    "    // Entries\n"
    "    if (data.parent != null) {\n"
    "      h += '<div class=\"tlc-ds-entry\" data-ds-nav=\"' + _esc(data.parent) + '\">';\n"
    "      h += '<span class=\"ds-icon\">↑</span>';\n"
    "      h += '<span class=\"ds-name\" style=\"color:var(--text-muted)\">..</span>';\n"
    "      h += '</div>';\n"
    "    }\n"
    "    if (!data.entries || data.entries.length === 0) {\n"
    "      h += '<div class=\"tlc-ds-empty\">Empty directory</div>';\n"
    "    } else {\n"
    "      data.entries.forEach(function(e) {\n"
    "        var isDir = (e.type === 'dir');\n"
    "        // Input mode: a folder the host can't open is a dead end — skip it entirely.\n"
    "        // undefined => accessible (older host without the flag), so only an explicit\n"
    "        // false hides it; files and accessible dirs render as normal.\n"
    "        if (isDir && purpose !== 'output' && e.accessible === false) { return; }\n"
    "        // Output mode: show EVERY folder, but flag one that can't be written to so\n"
    "        // the user still sees it (and can descend to a writable subdir). undefined =>\n"
    "        // writable (older host), so only an explicit false flags it.\n"
    "        var flagged = (isDir && purpose === 'output' && e.writable === false);\n"
    "        h += '<div class=\"tlc-ds-entry' + (flagged ? ' tlc-ds-entry-disabled' : '') + '\"';\n"
    "        if (isDir) {\n"
    "          // Navigable in both modes: a flagged (non-writable) folder stays clickable\n"
    "          // so the user can descend into it to find a writable subdirectory.\n"
    "          h += ' data-ds-nav=\"' + _esc(e.url || (data.path.replace(/\\/$/, '') + '/' + e.name)) + '\"';\n"
    "        }\n"
    "        if (flagged) h += ' title=\"Not writable — you may not be able to save here\"';\n"
    "        h += '>';\n"
    "        var icon = isDir ? (flagged ? '🔒' : '📁') : '📄';\n"
    "        h += '<span class=\"ds-icon\">' + icon + '</span>';\n"
    "        h += '<span class=\"ds-name\">' + _esc(e.name) + (e.type === 'dir' ? '/' : '') + '</span>';\n"
    "        if (e.size != null) h += '<span class=\"ds-size\">' + _fmtSize(e.size) + '</span>';\n"
    "        if (e.type === 'file') {\n"
    "          h += '<button type=\"button\" class=\"ds-select-btn\" data-ds-select=\"'"
    "             + _esc(e.url || (data.path.replace(/\\/$/, '') + '/' + e.name)) + '\">Select</button>';\n"
    "        }\n"
    "        h += '</div>';\n"
    "      });\n"
    "    }\n"
    "    if (data.truncated) h += '<div class=\"tlc-ds-filter-note\">More items than shown here.</div>';\n"
    "    panel.innerHTML = h;\n"
    "\n"
    "    // Location change: this compute, or a bucket\n"
    "    var locSel = panel.querySelector('[data-ds-loc]');\n"
    "    if (locSel) locSel.addEventListener('change', function() {\n"
    "      var v = locSel.value;\n"
    "      if (v === 'local') { _loc = { kind: 'local' }; _browseTo('~'); }\n"
    "      else { _loc = ((window._tlcDsLocations || {}).list || [])[parseInt(v, 10)] || { kind: 'local' }; "
    "_browseTo(_loc.kind === 'bucket' ? _loc.url : '~'); }\n"
    "    });\n"
    "    // Bind navigation clicks\n"
    "    panel.querySelectorAll('[data-ds-nav]').forEach(function(el) {\n"
    "      el.addEventListener('click', function(ev) {\n"
    "        ev.stopPropagation();\n"
    "        _browseTo(el.getAttribute('data-ds-nav'));\n"
    "      });\n"
    "    });\n"
    "    // Bind select buttons\n"
    "    panel.querySelectorAll('[data-ds-select]').forEach(function(el) {\n"
    "      el.addEventListener('click', function(ev) {\n"
    "        ev.stopPropagation();\n"
    "        input.value = el.getAttribute('data-ds-select');\n"
    "        _panelOpen = false;\n"
    "        panel.classList.remove('open');\n"
    "        input.dispatchEvent(new Event('input', {bubbles: true}));\n"
    "        input.dispatchEvent(new Event('change', {bubbles: true}));\n"
    "      });\n"
    "    });\n"
    "    // Bind select-folder button\n"
    "    panel.querySelectorAll('[data-ds-select-folder]').forEach(function(el) {\n"
    "      el.addEventListener('click', function(ev) {\n"
    "        ev.stopPropagation();\n"
    "        input.value = el.getAttribute('data-ds-select-folder');\n"
    "        _panelOpen = false;\n"
    "        panel.classList.remove('open');\n"
    "        input.dispatchEvent(new Event('input', {bubbles: true}));\n"
    "        input.dispatchEvent(new Event('change', {bubbles: true}));\n"
    "      });\n"
    "    });\n"
    "  }\n"
    "\n"
    "  // Upload zone\n"
    "  if (uploadBtn && uploadZone) {\n"
    "    var fileInput = document.getElementById(idPrefix + '-ds-file-input');\n"
    "    var uploadInfo = document.getElementById(idPrefix + '-ds-upload-info');\n"
    "\n"
    "    uploadBtn.addEventListener('click', function() {\n"
    "      var isOpen = uploadZone.classList.toggle('open');\n"
    "      if (isOpen) { panel.classList.remove('open'); _panelOpen = false; }\n"
    "    });\n"
    "\n"
    "    uploadZone.addEventListener('click', function() { fileInput.click(); });\n"
    "    uploadZone.addEventListener('dragover', function(ev) {\n"
    "      ev.preventDefault(); uploadZone.classList.add('dragging');\n"
    "    });\n"
    "    uploadZone.addEventListener('dragleave', function() {\n"
    "      uploadZone.classList.remove('dragging');\n"
    "    });\n"
    "    uploadZone.addEventListener('drop', function(ev) {\n"
    "      ev.preventDefault(); uploadZone.classList.remove('dragging');\n"
    "      if (ev.dataTransfer.files.length > 0) _uploadFile(ev.dataTransfer.files[0]);\n"
    "    });\n"
    "    fileInput.addEventListener('change', function() {\n"
    "      if (fileInput.files.length > 0) _uploadFile(fileInput.files[0]);\n"
    "    });\n"
    "\n"
    "    function _uploadFile(file) {\n"
    "      uploadInfo.style.display = '';\n"
    "      uploadInfo.textContent = 'Uploading ' + file.name + '…';\n"
    "      uploadZone.style.opacity = '0.6';\n"
    "      uploadZone.style.pointerEvents = 'none';\n"
    "\n"
    "      var formData = new FormData();\n"
    "      formData.append('data', file);\n"
    "\n"
    "      API.authFetch(computeUrl + '/api/plugins/' + pluginId + '/upload-temp', {\n"
    "        method: 'POST',\n"
    "        body: formData,\n"
    "      })\n"
    "      .then(function(r) { return r.json(); })\n"
    "      .then(function(result) {\n"
    "        input.value = result.path;\n"
    "        uploadInfo.innerHTML = '<span style=\"color:var(--success)\">✓</span> '"
    "          + _esc(file.name) + ' <span style=\"color:var(--text-muted)\">→ '"
    "          + _esc(result.path) + '</span>';\n"
    "        uploadZone.classList.remove('open');\n"
    "        input.dispatchEvent(new Event('input', {bubbles: true}));\n"
    "        input.dispatchEvent(new Event('change', {bubbles: true}));\n"
    "      })\n"
    "      .catch(function(err) {\n"
    "        uploadInfo.innerHTML = '<span style=\"color:var(--error)\">Upload failed:</span> '"
    "          + _esc(String(err));\n"
    "      })\n"
    "      .finally(function() {\n"
    "        uploadZone.style.opacity = '';\n"
    "        uploadZone.style.pointerEvents = '';\n"
    "      });\n"
    "    }\n"
    "  }\n"
    "\n"
    "  // Close panel on outside click\n"
    "  document.addEventListener('click', function(ev) {\n"
    "    if (!_panelOpen) return;\n"
    "    var wrapper = input.closest('.tlc-ds-wrapper');\n"
    "    if (wrapper && !wrapper.contains(ev.target)) {\n"
    "      _panelOpen = false;\n"
    "      panel.classList.remove('open');\n"
    "      if (uploadZone) uploadZone.classList.remove('open');\n"
    "    }\n"
    "  });\n"
    "}\n"
    "\n"
    "function _tlcGetDataSourceValue(idPrefix) {\n"
    "  var el = document.getElementById(idPrefix);\n"
    "  return el ? el.value.trim() : '';\n"
    "}\n"
    "\n"
    "function _tlcSetDataSourceValue(idPrefix, value) {\n"
    "  var el = document.getElementById(idPrefix);\n"
    "  if (el) {\n"
    "    el.value = value || '';\n"
    "    el.dispatchEvent(new Event('input', {bubbles: true}));\n"
    "    el.dispatchEvent(new Event('change', {bubbles: true}));\n"
    "  }\n"
    "}\n"
)
# fmt: on


def data_source_ui_script() -> str:
    """Return the shared data-source UI JavaScript block."""
    return DATA_SOURCE_UI_JS
