# Copyright 2026 3LC Inc.
# SPDX-License-Identifier: Apache-2.0
r"""Shared UI component for data-source inputs (files and folders on the compute node).

Generates the HTML + JS block that plugins embed in their UI fragments.
This ensures a consistent file/folder selection experience across every plugin
that needs to reference data on the compute node — local paths, S3 URLs, or
browser-uploaded files all resolve to a compute-visible location.

Usage in a plugin's ``get_ui_fragment()``::

    from tlc_plugin_sdk.shared.data_source_ui import data_source_ui_script
    from tlc_plugin_sdk.shared.ui_inject import inject_scripts

    raw = Path("ui.html").read_text()
    html = inject_scripts(raw, data_source_ui_script())

Then in the plugin's ``ui.html`` JavaScript:

.. code-block:: javascript

    // Render a data-source input
    var html = _tlcDataSourceHtml('my-field', {
        placeholder: 'Path to dataset YAML...',
        accept: '*.yaml,*.yml',      // glob filter for the browser
        allowUpload: false,           // show upload toggle? (never shown for a node run)
    });
    container.innerHTML = html;

    // Bind the browse/upload handlers (call AFTER inserting into DOM)
    _tlcBindDataSource('my-field', computeUrl, pluginId, {
        accept: '*.yaml,*.yml',
        mode: 'file',                 // 'file' or 'folder' ('dir' is read as 'folder')
        purpose: 'input',             // 'input' (default) or 'output'
    });

    // Read the value at submit time
    var path = _tlcGetDataSourceValue('my-field');

The widget requires the plugin to serve the ``/browse`` and (optionally)
``/upload-temp`` routes from :mod:`~tlc_plugin_sdk.shared.data_source_routes`.

Browsing is not only the compute's own disk: the panel's location bar lists every
bucket the compute service knows (its generic ``/api/infra/storage`` surface, the same
locations as the Hub's Storage page), and browsing one of them goes through the
provider's ``/list`` route **through the Connection the bucket was listed through** —
the listing tags each bucket with its ``connection_id``, and the widget names it on
every later call, as a host with a Config Service requires. Picking a bucket folder
writes its URL (``s3://…``) into the field, which plugins already accept. Volumes are
not offered.

The locations follow the run target, the Hub's "Run on:" choice
(``PLUGIN_API.getRunTarget()``, re-read on ``onRunTargetChange``):

- **A node.** The node's own disk comes first ("<label> (node)"), browsed through the host's
  ``/api/infra/nodes/{id}/files`` under the folder the node agent browses; the buckets follow, each
  saying whether that node can read it when the node's storage probe covers it. There is no
  "This computer" and no Upload: a node cannot read either.
- **The compute host.** Its disk is "This computer" when the compute URL is a loopback address
  (the browser and the compute are the same machine), else it is offered under the Hub's name for
  the host (``getRunTarget().label``); the buckets follow.

A value the run target cannot reach — a folder picked on this computer and then a node chosen, a
typed path the node does not have, a bucket the node's probe says it cannot read — gets a note
under the field naming why and what the run will do. On a Hub without ``getRunTarget`` the widget
behaves as before run targets: the compute's disk only when it is this computer, then the buckets.
Without an infrastructure plugin (or on a host without that surface) the bar shows only
"This computer".
"""

from __future__ import annotations

from tlc_plugin_sdk.shared.run_target_ui import RUN_TARGET_JS

# fmt: off
DATA_SOURCE_UI_JS = RUN_TARGET_JS + (
    "// -- Shared Data Source UI ------\n"
    "(function(){\n"
    "var st=document.createElement('style');st.textContent=\n"
    "'.tlc-ds-wrapper{position:relative}'"
    "+'.tlc-ds-browse-panel{position:absolute;left:0;right:0;z-index:100;'"
    "+' border:1px solid var(--border);border-radius:6px;'"
    "+' margin-top:4px;max-height:320px;overflow-y:auto;background:var(--bg-card);'"
    "+' font-size:12px;display:none;'"
    "+' box-shadow:0 4px 16px rgba(0,0,0,.12)}'"
    "+'.tlc-ds-browse-panel.open{display:block}'"
    "+'.tlc-ds-breadcrumb{display:flex;align-items:center;gap:2px;padding:8px 10px;'"
    "+' border-bottom:1px solid var(--border);font-size:11px;flex-wrap:wrap;'"
    "+' background:var(--bg-secondary,rgba(0,0,0,.02))}'"
    "+'.tlc-ds-breadcrumb span{cursor:pointer;color:var(--accent);font-weight:500}'"
    "+'.tlc-ds-breadcrumb span:hover{text-decoration:underline}'"
    "+'.tlc-ds-breadcrumb .sep{color:var(--text-muted);cursor:default;margin:0 1px}'"
    "+'.tlc-ds-breadcrumb .sep:hover{text-decoration:none}'"
    "+'.tlc-ds-filter-note{padding:4px 10px;font-size:10px;color:var(--text-muted);'"
    "+' border-bottom:1px solid var(--border-light,rgba(0,0,0,.04))}'"
    "+'.tlc-ds-entry{display:flex;align-items:center;gap:8px;padding:5px 10px;'"
    "+' cursor:pointer;border-bottom:1px solid var(--border-light,rgba(0,0,0,.04))}'"
    "+'.tlc-ds-entry:hover{background:var(--golden-light,rgba(217,119,6,.06))}'"
    "+'.tlc-ds-entry:last-child{border-bottom:none}'"
    # Folders the compute process can't open (e.g. macOS TCC-protected packages):
    # dimmed, no pointer, and the golden hover is suppressed so they don't invite a click.
    "+'.tlc-ds-entry-disabled{cursor:default;opacity:.5}'"
    "+'.tlc-ds-entry-disabled:hover{background:transparent}'"
    "+'.tlc-ds-entry .ds-icon{flex-shrink:0;width:16px;text-align:center;font-size:13px}'"
    "+'.tlc-ds-entry .ds-name{flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}'"
    "+'.tlc-ds-entry .ds-size{font-size:10px;color:var(--text-muted);flex-shrink:0}'"
    # Scoped to the panel (not .tlc-ds-entry): the folder-mode select button renders in
    # the BREADCRUMB — entry-scoped rules left it a naked native <button>.
    "+'.tlc-ds-browse-panel .ds-select-btn{font-size:10px;padding:2px 8px;border:1px solid var(--border);'"
    "+' border-radius:3px;background:var(--bg-card);cursor:pointer;color:var(--accent);font-weight:600;flex-shrink:0}'"
    "+'.tlc-ds-browse-panel .ds-select-btn:hover{background:var(--accent);color:#fff;border-color:var(--accent)}'"
    "+'.tlc-ds-empty{padding:16px;text-align:center;color:var(--text-muted);font-size:11px}'"
    "+'.tlc-ds-error{padding:10px;color:var(--error,#ef4444);font-size:11px}'"
    "+'.tlc-ds-upload-zone{position:absolute;left:0;right:0;z-index:100;'"
    "+' border:2px dashed var(--border);border-radius:6px;padding:20px;'"
    "+' text-align:center;cursor:pointer;transition:border-color .15s,background .15s;'"
    "+' margin-top:4px;display:none;font-size:12px;background:var(--bg-card);'"
    "+' box-shadow:0 4px 16px rgba(0,0,0,.12)}'"
    "+'.tlc-ds-upload-zone.open{display:block}'"
    "+'.tlc-ds-upload-zone:hover{border-color:var(--accent);background:var(--accent-light,rgba(42,74,97,.04))}'"
    "+'.tlc-ds-upload-zone.dragging{border-color:var(--accent);background:var(--accent-light,rgba(42,74,97,.08))}'"
    "+'.tlc-ds-upload-info{font-size:11px;color:var(--text-muted);margin-top:4px;display:none}'"
    "+'.tlc-ds-actions{display:flex;gap:6px;align-items:center}'"
    "+'.tlc-ds-loc{display:flex;align-items:center;gap:8px;padding:6px 10px;'"
    "+' border-bottom:1px solid var(--border);background:var(--bg-card);font-size:11px}'"
    "+'.tlc-ds-loc label{color:var(--text-muted);white-space:nowrap}'"
    "+'.tlc-ds-loc select{flex:1;min-width:0;font:inherit;font-size:11.5px;padding:3px 6px;'"
    "+' border:1px solid var(--border);border-radius:4px;background:var(--bg);color:var(--text)}'"
    "+'.tlc-ds-loc-note{padding:4px 10px;font-size:10.5px;color:var(--text-muted);'"
    "+' border-bottom:1px solid var(--border)}'"
    # What the run target cannot reach, under the field: a sentence, not an error — the run says the rest.
    "+'.tlc-ds-reach{margin-top:4px;font-size:11px;line-height:1.45;color:var(--warning,#b45309)}';\n"
    "document.head.appendChild(st)})();\n"
    "\n"
    "function _tlcDataSourceHtml(idPrefix, config) {\n"
    "  config = config || {};\n"
    "  var ph = config.placeholder || 'Path on compute node or URL…';\n"
    "  var allowUpload = config.allowUpload || false;\n"
    "  var accept = config.accept || '';\n"
    "  var h = '';\n"
    "  h += '<div class=\"tlc-ds-wrapper\">';\n"
    "  h += '<div class=\"tlc-ds-actions\">';\n"
    "  h += '<input type=\"text\" id=\"' + idPrefix + '\" class=\"form-control\"';\n"
    "  h += ' placeholder=\"' + ph + '\" style=\"flex:1\">';\n"
    "  h += '<button type=\"button\" class=\"btn btn-secondary btn-sm\" id=\"' + idPrefix + '-ds-browse-btn\"';\n"
    "  h += ' style=\"white-space:nowrap\">Browse…</button>';\n"
    "  if (allowUpload) {\n"
    "    h += '<button type=\"button\" class=\"btn btn-secondary btn-sm\" id=\"' + idPrefix + '-ds-upload-btn\"';\n"
    "    h += ' style=\"white-space:nowrap\">Upload</button>';\n"
    "  }\n"
    "  h += '</div>';\n"
    "  // What the run target cannot reach (hidden until there is something to say)\n"
    "  h += '<div class=\"tlc-ds-reach\" id=\"' + idPrefix + '-ds-reach\" style=\"display:none\"></div>';\n"
    "  // Browse panel (inline, hidden by default)\n"
    "  h += '<div class=\"tlc-ds-browse-panel\" id=\"' + idPrefix + '-ds-panel\"></div>';\n"
    "  // Upload zone (hidden by default)\n"
    "  if (allowUpload) {\n"
    "    var acceptAttr = accept ? accept.split(',').map(function(g){"
    " return g.trim().replace('*',''); }).join(',') : '';\n"
    "    h += '<div class=\"tlc-ds-upload-zone\" id=\"' + idPrefix + '-ds-upload-zone\">';\n"
    "    h += '<div style=\"font-weight:600;margin-bottom:4px\">Drop file here</div>';\n"
    "    h += '<div style=\"color:var(--text-muted)\">or click to browse';\n"
    "    if (accept) h += ' — ' + accept;\n"
    "    h += '</div>';\n"
    "    h += '<input type=\"file\" id=\"' + idPrefix + '-ds-file-input\"';\n"
    "    if (acceptAttr) h += ' accept=\"' + acceptAttr + '\"';\n"
    "    h += ' style=\"display:none\">';\n"
    "    h += '</div>';\n"
    "    h += '<div class=\"tlc-ds-upload-info\" id=\"' + idPrefix + '-ds-upload-info\"></div>';\n"
    "  }\n"
    "  h += '</div>';  // close .tlc-ds-wrapper\n"
    "  return h;\n"
    "}\n"
    "\n"
    "// What a node can read, from its storage probe (node health `storage` in the host's /api/infra/status,\n"
    "// keyed by the root it probed): 'ok', 'denied' (denied or unreachable), or '' when no probe covers the\n"
    "// bucket. A probe of a prefix speaks for its bucket.\n"
    "function _tlcDsBucketReach(url, storage) {\n"
    "  var want = _tlcStorageOf(url), state = '', detail = '';\n"
    "  if (want === 'local') return { state: '', detail: '' };\n"
    "  Object.keys(storage || {}).forEach(function(root) {\n"
    "    var probe = storage[root] || {};\n"
    "    if (_tlcStorageOf(root) !== want) return;\n"
    "    if (probe.state === 'ok') { state = 'ok'; detail = String(probe.detail || ''); }\n"
    "    else if ((probe.state === 'denied' || probe.state === 'unreachable') && state !== 'ok') {\n"
    "      state = 'denied'; detail = String(probe.detail || '');\n"
    "    }\n"
    "  });\n"
    "  return { state: state, detail: detail };\n"
    "}\n"
    "\n"
    "// The Location bar for a run target (_tlcRunTarget(); null = a Hub that has none). buckets: the compute's\n"
    "// bucket locations. here: the compute host is this browser's machine. node: what the host reports about\n"
    "// the target node ({label, files_root, storage}), or null.\n"
    "// - A node: its own disk first, then the buckets, each saying whether that node can read it. Never this\n"
    "//   computer: a node cannot read it.\n"
    "// - The compute host: its disk as \"This computer\" when that is what it is, else under the Hub's name for\n"
    "//   it, then the buckets. A Hub without a run target names none, so the disk is offered only when here.\n"
    "function _tlcDsLocationList(target, buckets, here, node) {\n"
    "  var out = [];\n"
    "  buckets = buckets || [];\n"
    "  if (target && target.target === 'node') {\n"
    "    var name = target.label || (node && node.label) || target.node_id;\n"
    "    var root = String(target.files_root || (node && node.files_root) || '');\n"
    "    if (root.length > 1) root = root.replace(/\\/$/, '');\n"
    "    out.push({ kind: 'node', node_id: target.node_id, name: name, label: name + ' (node)', files_root: root });\n"
    "    buckets.forEach(function(b) {\n"
    "      var reach = _tlcDsBucketReach(b.url, node && node.storage);\n"
    "      var loc = {};\n"
    "      Object.keys(b).forEach(function(k) { loc[k] = b[k]; });\n"
    "      loc.reach = reach.state;\n"
    "      loc.reach_detail = reach.detail;\n"
    "      loc.note = reach.state === 'ok' ? 'readable from ' + name : reach.state === 'denied' ? name + ' cannot read "
    "this' : '';\n"
    "      out.push(loc);\n"
    "    });\n"
    "    return out;\n"
    "  }\n"
    "  if (here) out.push({ kind: 'local', name: 'This computer', label: 'This computer' });\n"
    "  else if (target && target.label) out.push({ kind: 'local', name: target.label, label: target.label });\n"
    "  return out.concat(buckets);\n"
    "}\n"
    "\n"
    "// The listing URL for one folder of a location: a node's disk through the host, a bucket through its\n"
    "// provider, the compute host's disk through the plugin's own /browse.\n"
    "function _tlcDsBrowseUrl(loc, computeUrl, pluginId, path, glob, purpose) {\n"
    "  if (loc.kind === 'node') {\n"
    "    return computeUrl + '/api/infra/nodes/' + encodeURIComponent(loc.node_id) + '/files?path=' + "
    "encodeURIComponent(path || '');\n"
    "  }\n"
    "  if (loc.kind === 'bucket') {\n"
    "    var url = computeUrl + '/api/infra/storage/' + encodeURIComponent(loc.plugin_id) + '/list?url='\n"
    "      + encodeURIComponent(String(path || loc.url).replace(/\\/$/, '') + '/');\n"
    "    // Name the Connection this bucket was listed through — a host with a Config Service\n"
    "    // refuses a storage call that names none.\n"
    "    if (loc.connection_id) url += '&connection_id=' + encodeURIComponent(loc.connection_id);\n"
    "    return url;\n"
    "  }\n"
    "  var local = computeUrl + '/api/plugins/' + pluginId + '/browse?path=' + encodeURIComponent(path);\n"
    "  if (glob) local += '&glob=' + encodeURIComponent(glob);\n"
    "  return local + '&purpose=' + encodeURIComponent(purpose || 'input');\n"
    "}\n"
    "\n"
    "// The note for a value the run target cannot reach, or ''. ctx: {target, where, whereLabel, hostLabel,\n"
    "// nodeLabel, probe, check}. where is the location the value was picked in ('local' for the compute host,\n"
    "// 'node:<id>', 'bucket'; '' when it was typed or restored), probe the target node's reach for a bucket\n"
    "// value ({state, detail}), check the node's path-check answer for a typed path.\n"
    "function _tlcDsReachNote(value, ctx) {\n"
    "  value = String(value || '').trim();\n"
    "  ctx = ctx || {};\n"
    "  var t = ctx.target;\n"
    "  if (!value || !t) return '';\n"
    "  var host = ctx.hostLabel || 'the compute host';\n"
    "  var node = ctx.nodeLabel || 'the node';\n"
    "  var where = String(ctx.where || '');\n"
    "  if (value.indexOf('://') !== -1) {\n"
    "    if (t.target !== 'node' || !ctx.probe || ctx.probe.state !== 'denied') return '';\n"
    "    return node + ' cannot read this bucket' + (ctx.probe.detail ? ' (' + ctx.probe.detail + ')' : '')\n"
    "      + ', so a run there can neither stream nor copy it. Choose data ' + node + ' can read, or give it "
    "access.';\n"
    "  }\n"
    "  if (t.target === 'node') {\n"
    "    if (where === 'local') {\n"
    "      return 'This is on ' + host + ', which ' + node + ' cannot read: a run on ' + node + ' is refused for it.'\n"
    "        + ' Put the data in a bucket, or choose a folder on ' + node + '.';\n"
    "    }\n"
    "    if (where.indexOf('node:') === 0 && where !== 'node:' + t.node_id) {\n"
    "      return 'This is on ' + (ctx.whereLabel || 'another node') + ', not on ' + node + '. A run on ' + node\n"
    "        + ' looks for it there and is refused if it is missing.';\n"
    "    }\n"
    "    if (ctx.check && ctx.check.checked !== false && ctx.check.exists === false) {\n"
    "      return node + ' has no ' + value + '. A run there is refused; choose a folder on ' + node + ', or a "
    "bucket.';\n"
    "    }\n"
    "    return '';\n"
    "  }\n"
    "  if (where.indexOf('node:') === 0) {\n"
    "    return 'This is on ' + (ctx.whereLabel || 'a node') + ', not on ' + host + '. A run on ' + host\n"
    "      + ' looks for it on ' + host + ' and is refused if it is missing.';\n"
    "  }\n"
    "  return '';\n"
    "}\n"
    "\n"
    "function _tlcBindDataSource(idPrefix, computeUrl, pluginId, config) {\n"
    "  config = config || {};\n"
    "  var glob = config.accept || '';\n"
    "  // 'dir' is what some plugins pass for a folder picker: it means 'folder'.\n"
    "  var mode = config.mode === 'dir' ? 'folder' : (config.mode || 'file');\n"
    "  var purpose = config.purpose || 'input';\n"
    "  var input = document.getElementById(idPrefix);\n"
    "  var browseBtn = document.getElementById(idPrefix + '-ds-browse-btn');\n"
    "  var panel = document.getElementById(idPrefix + '-ds-panel');\n"
    "  var uploadBtn = document.getElementById(idPrefix + '-ds-upload-btn');\n"
    "  var uploadZone = document.getElementById(idPrefix + '-ds-upload-zone');\n"
    "  var reachEl = document.getElementById(idPrefix + '-ds-reach');\n"
    "  var API = window.PLUGIN_API;\n"
    "\n"
    "  // Format file sizes\n"
    "  function _fmtSize(bytes) {\n"
    "    if (bytes == null) return '';\n"
    "    if (bytes < 1024) return bytes + ' B';\n"
    "    if (bytes < 1048576) return (bytes / 1024).toFixed(1) + ' KB';\n"
    "    return (bytes / 1048576).toFixed(1) + ' MB';\n"
    "  }\n"
    "\n"
    "  function _esc(s) {\n"
    "    if (!s) return '';\n"
    "    var d = document.createElement('div');\n"
    "    d.textContent = s;\n"
    "    return d.innerHTML;\n"
    "  }\n"
    "\n"
    "  // Locations follow where the run goes (see _tlcDsLocationList): the target node's disk and the buckets\n"
    "  // for a node run; for a run on the compute host, its disk — \"This computer\" only when the compute runs\n"
    "  // on this machine (a cloud workspace has a disk too, but it is not the person's computer) — and the\n"
    "  // buckets. The buckets are every one the compute service lists (the Hub's Storage page shows the same).\n"
    "  var _here = _tlcComputeIsHere(computeUrl);\n"
    "  var _loc = { kind: 'none' };\n"
    "  var _list = [];\n"
    "  function _hostLabel(t) {\n"
    "    if (_here) return 'this computer';\n"
    "    return (t && t.target === 'local' && t.label) || 'the compute host';\n"
    "  }\n"
    "  function _buckets() {\n"
    "    var cache = window._tlcDsLocations;\n"
    "    if (cache && (Date.now() - cache.at) < 60000) return Promise.resolve(cache.list);\n"
    "    return API.authFetch(computeUrl + '/api/infra/storage')\n"
    "      .then(function(r) { return r.ok ? r.json() : { storage: [], providers: [] }; })\n"
    "      .then(function(out) {\n"
    "        var byPlugin = {};\n"
    "        // Provider rows are per Connection: prefer one that can browse over one whose\n"
    "        // listing errored for another Connection, so a single bad grant doesn't hide a provider.\n"
    "        (out.providers || []).forEach(function(p) { if (!byPlugin[p.plugin_id] || p.browse) byPlugin[p.plugin_id] "
    "= p; });\n"
    "        var list = (out.storage || []).filter(function(s) {\n"
    "          // Only bucket URLs: what a run reads as an s3://-style URL, not volumes or node disks.\n"
    "          return s.kind === 'bucket' && s.url && (byPlugin[s.plugin_id] || {}).browse;\n"
    "        }).map(function(s) {\n"
    "          // Each bucket was listed through a Connection; every later call about it names that\n"
    "          // Connection (empty on a host whose storage is its own identity).\n"
    "          return { kind: 'bucket', plugin_id: s.plugin_id, url: String(s.url).replace(/\\/$/, ''),\n"
    "                   connection_id: s.connection_id || '', connection_name: s.connection_name || '',\n"
    "                   name: s.name || s.id, label: (byPlugin[s.plugin_id] || {}).label || 'bucket', root: "
    "!!s.project_root };\n"
    "        });\n"
    "        window._tlcDsLocations = { at: Date.now(), list: list };\n"
    "        return list;\n"
    "      })\n"
    "      .catch(function() { return []; });\n"
    "  }\n"
    "  // What the host reports about a node: its label, the folder its agent browses, and its storage probe.\n"
    "  function _nodeInfo(nodeId) {\n"
    "    if (!nodeId) return Promise.resolve(null);\n"
    "    var cache = window._tlcDsNodes;\n"
    "    if (cache && cache.base === computeUrl && (Date.now() - cache.at) < 15000) return "
    "Promise.resolve(cache.nodes[nodeId] || null);\n"
    "    return API.authFetch(computeUrl + '/api/infra/status')\n"
    "      .then(function(r) { return r.ok ? r.json() : { nodes: [] }; })\n"
    "      .then(function(st) {\n"
    "        var nodes = {};\n"
    "        (st.nodes || []).forEach(function(n) {\n"
    "          var h = n.health || {};\n"
    "          nodes[n.id] = { label: n.label || '', files_root: h.files_root || '', storage: h.storage || {} };\n"
    "        });\n"
    "        window._tlcDsNodes = { at: Date.now(), base: computeUrl, nodes: nodes };\n"
    "        return nodes[nodeId] || null;\n"
    "      })\n"
    "      .catch(function() { return null; });\n"
    "  }\n"
    "  function _locations() {\n"
    "    var t = _tlcRunTarget();\n"
    "    return Promise.all([_buckets(), _nodeInfo(t && t.target === 'node' ? t.node_id : '')]).then(function(got) {\n"
    "      _list = _tlcDsLocationList(t, got[0], _here, got[1]);\n"
    "      return _list;\n"
    "    });\n"
    "  }\n"
    "  function _sameLoc(a, b) {\n"
    "    if (!a || !b || a.kind !== b.kind) return false;\n"
    "    if (a.kind === 'bucket') return a.url === b.url && (a.connection_id || '') === (b.connection_id || '');\n"
    "    return a.kind !== 'node' || a.node_id === b.node_id;\n"
    "  }\n"
    "  function _defaultLoc() {\n"
    "    // A node run opens the node; a run on the compute host opens this computer, else the project root's\n"
    "    // bucket (or the first one), else the host's disk under its name.\n"
    "    if (_list[0] && _list[0].kind === 'node') return _list[0];\n"
    "    var disk = _list.filter(function(l) { return l.kind === 'local'; })[0];\n"
    "    if (disk && _here) return disk;\n"
    "    var buckets = _list.filter(function(l) { return l.kind === 'bucket'; });\n"
    "    return buckets.filter(function(l) { return l.root; })[0] || buckets[0] || disk || { kind: 'none' };\n"
    "  }\n"
    "  function _locationFor(value) {\n"
    "    // A value inside a known bucket opens that bucket; a path opens the disk the run reads.\n"
    "    for (var i = 0; i < _list.length; i++) {\n"
    "      var l = _list[i];\n"
    "      if (l.kind === 'bucket' && (value === l.url || value.indexOf(l.url + '/') === 0)) return l;\n"
    "    }\n"
    "    if (value && value.indexOf('://') === -1) {\n"
    "      var disk = _list.filter(function(l) { return l.kind === 'node' || l.kind === 'local'; })[0];\n"
    "      if (disk) return disk;\n"
    "    }\n"
    "    return _defaultLoc();\n"
    "  }\n"
    "  function _startPath(value) {\n"
    "    if (_loc.kind === 'bucket') {\n"
    "      // A file URL browses its folder; a folder URL browses itself.\n"
    "      var at = value;\n"
    "      if (mode === 'file' || /\\.[A-Za-z0-9]{1,6}$/.test(at)) at = at.replace(/\\/[^/]*$/, '');\n"
    "      return at.indexOf(_loc.url) === 0 ? at : _loc.url;\n"
    "    }\n"
    "    if (value.indexOf('://') !== -1) return _loc.kind === 'node' ? _loc.files_root : '~';  // nothing here lists "
    "it\n"
    "    if (_loc.kind === 'node') {\n"
    "      // A path under the node's browsable folder opens its parent; anything else opens that folder.\n"
    "      var root = _loc.files_root;\n"
    "      var inside = value.charAt(0) === '/' && (!root || value === root || value.indexOf(root.replace(/\\/$/, '') "
    "+ '/') === 0);\n"
    "      return inside && value.lastIndexOf('/') > 0 ? value.substring(0, value.lastIndexOf('/')) : root;\n"
    "    }\n"
    "    if (!value) return '~';\n"
    "    // If the current value is a file path, browse its parent directory\n"
    "    var lastSlash = value.lastIndexOf('/');\n"
    "    return lastSlash > 0 ? value.substring(0, lastSlash) : value;\n"
    "  }\n"
    "  function _nowhereNote() {\n"
    "    var host = String(computeUrl || '').replace(/^https?:\\/\\//, '').replace(/[/:].*$/, '');\n"
    "    return '<div class=\"tlc-ds-empty\">The compute service runs on ' + _esc(host || 'another machine')\n"
    "      + ', not on your computer, so there is no folder of yours to browse here. Put the data on a bucket first'\n"
    "      + ' (Storage page), then choose it here, or type its URL.</div>';\n"
    "  }\n"
    "  function _globToRegex(pattern) {\n"
    "    var parts = pattern.split(',').map(function(g) { return g.trim(); }).filter(Boolean);\n"
    "    if (!parts.length) return null;\n"
    "    return new RegExp('^(?:' + parts.map(function(g) {\n"
    "      return g.replace(/[.+^${}()|[\\]\\\\]/g, '\\\\$&').replace(/\\*/g, '.*').replace(/\\?/g, '.');\n"
    "    }).join('|') + ')$', 'i');\n"
    "  }\n"
    "\n"
    "  // Browse panel\n"
    "  var _panelOpen = false;\n"
    "  function _open() {\n"
    "    panel.innerHTML = '<div class=\"tlc-ds-empty\">Loading…</div>';\n"
    "    _locations().then(function() {\n"
    "      var value = input.value.trim();\n"
    "      _loc = _locationFor(value);\n"
    "      if (_loc.kind === 'none') { panel.innerHTML = _nowhereNote(); return; }\n"
    "      _browseTo(_startPath(value), true);\n"
    "    });\n"
    "  }\n"
    "  browseBtn.addEventListener('click', function() {\n"
    "    _panelOpen = !_panelOpen;\n"
    "    panel.classList.toggle('open', _panelOpen);\n"
    "    if (uploadZone) { uploadZone.classList.remove('open'); }\n"
    "    if (!_panelOpen) return;\n"
    "    _open();\n"
    "  });\n"
    "\n"
    "  // opening: the first listing of an open panel, which falls back to the location's top folder when the\n"
    "  // value it started from is not there.\n"
    "  function _browseTo(dirPath, opening) {\n"
    "    panel.innerHTML = '<div class=\"tlc-ds-empty\">Loading…</div>';\n"
    "    if (_loc.kind === 'none') { panel.innerHTML = _nowhereNote(); return; }\n"
    "    if (_loc.kind === 'bucket') { _browseBucket(dirPath); return; }\n"
    "    if (_loc.kind === 'node') { _browseNode(dirPath, opening); return; }\n"
    "    API.authFetch(_tlcDsBrowseUrl(_loc, computeUrl, pluginId, dirPath, glob, purpose))\n"
    "      .then(function(r) { return r.json(); })\n"
    "      .then(function(data) {\n"
    "        if (data.error) {\n"
    "          panel.innerHTML = '<div class=\"tlc-ds-error\">' + _esc(data.error) + '</div>';\n"
    "          return;\n"
    "        }\n"
    "        _renderBrowse(data);\n"
    "      })\n"
    "      .catch(function(err) {\n"
    "        panel.innerHTML = '<div class=\"tlc-ds-error\">Failed to browse: ' + _esc(String(err)) + '</div>';\n"
    "      });\n"
    "  }\n"
    "\n"
    "  function _readJson(r) {\n"
    "    return r.json().then(function(j) { if (!r.ok) throw new Error(j.detail || ('HTTP ' + r.status)); return j; "
    "});\n"
    "  }\n"
    "\n"
    "  // One level of a bucket, through its provider, shaped like the local listing so one renderer serves both.\n"
    "  function _browseBucket(prefixUrl) {\n"
    "    var at = prefixUrl.replace(/\\/$/, '');\n"
    "    var re = glob ? _globToRegex(glob) : null;\n"
    "    API.authFetch(_tlcDsBrowseUrl(_loc, computeUrl, pluginId, at))\n"
    "      .then(_readJson)\n"
    "      .then(function(out) {\n"
    "        var entries = (out.prefixes || []).map(function(p) { return { name: p.name, type: 'dir', url: "
    "String(p.url).replace(/\\/$/, '') }; })\n"
    "          .concat((out.objects || []).filter(function(o) { return !re || re.test(o.name); })\n"
    "            .map(function(o) { return { name: o.name, type: 'file', size: o.size, url: o.url }; }));\n"
    "        var parent = at === _loc.url ? null : at.replace(/\\/[^/]*$/, '');\n"
    "        _renderBrowse({ path: at, root: _loc.url, parent: parent, entries: entries, truncated: !!out.truncated "
    "});\n"
    "      })\n"
    "      .catch(function(err) {\n"
    "        panel.innerHTML = '<div class=\"tlc-ds-error\">Could not read this folder: ' + _esc(String(err.message || "
    "err)) + '</div>';\n"
    "      });\n"
    "  }\n"
    "\n"
    "  // One level of the target node's disk, through the host ({path, root, dirs, files} from the node agent),\n"
    "  // confined to the folder the agent browses.\n"
    "  function _browseNode(dirPath, opening) {\n"
    "    var loc = _loc;\n"
    "    var re = glob ? _globToRegex(glob) : null;\n"
    "    API.authFetch(_tlcDsBrowseUrl(loc, computeUrl, pluginId, dirPath))\n"
    "      .then(_readJson)\n"
    "      .then(function(out) {\n"
    "        if (_loc !== loc) return;\n"
    "        var root = String(out.root || loc.files_root || '/');\n"
    "        var at = String(out.path || root);\n"
    "        var entries = (out.dirs || []).map(function(d) { return { name: d.name, type: 'dir', url: d.path }; })\n"
    "          .concat((out.files || []).filter(function(f) { return !re || re.test(f.name); })\n"
    "            .map(function(f) { return { name: f.name, type: 'file', size: f.size, url: f.path }; }));\n"
    "        var parent = at === root ? null : (at.replace(/\\/[^/]*$/, '') || '/');\n"
    "        _renderBrowse({ path: at, root: root, parent: parent, entries: entries, truncated: !!out.truncated });\n"
    "      })\n"
    "      .catch(function(err) {\n"
    "        if (_loc !== loc) return;\n"
    "        if (opening && dirPath) { _browseNode('', false); return; }  // the value is not on this node: start at "
    "its top\n"
    "        panel.innerHTML = '<div class=\"tlc-ds-error\">Could not read this folder on ' + _esc(loc.name) + ': '\n"
    "          + _esc(String(err.message || err)) + '</div>';\n"
    "      });\n"
    "  }\n"
    "\n"
    "  function _renderBrowse(data) {\n"
    "    var h = '';\n"
    "    // Location bar: the run target's disk and the buckets. Not drawn for this computer alone.\n"
    "    var locs = _list;\n"
    "    if (locs.length && !(locs.length === 1 && locs[0].kind === 'local' && _here)) {\n"
    "      // A provider with several Connections lists the same bucket more than once: the\n"
    "      // Connection name is what tells the twins apart, so show it only then.\n"
    "      var connsOf = {};\n"
    "      locs.forEach(function(l) { if (l.connection_id) { (connsOf[l.plugin_id] = connsOf[l.plugin_id] || "
    "{})[l.connection_id] = 1; } });\n"
    "      h += '<div class=\"tlc-ds-loc\"><label>Location</label><select data-ds-loc>';\n"
    "      locs.forEach(function(l, i) {\n"
    "        var text = l.label;\n"
    "        if (l.kind === 'bucket') {\n"
    "          var viaConn = Object.keys(connsOf[l.plugin_id] || {}).length > 1 && l.connection_name;\n"
    "          text = l.label + ' · ' + l.name + (viaConn ? ' — ' + l.connection_name : '') + (l.root ? ' (project "
    "root)' : '')\n"
    "            + (l.note ? ' — ' + l.note : '');\n"
    "        }\n"
    "        h += '<option value=\"' + i + '\"' + (_sameLoc(_loc, l) ? ' selected' : '') + '>' + _esc(text) + "
    "'</option>';\n"
    "      });\n"
    "      h += '</select></div>';\n"
    "      if (_loc.kind === 'bucket' && _loc.reach === 'denied') {\n"
    "        h += '<div class=\"tlc-ds-loc-note\">' + _esc(_loc.note + (_loc.reach_detail ? ': ' + _loc.reach_detail : "
    "'')) + '</div>';\n"
    "      }\n"
    "    }\n"
    "    // Breadcrumb — anchored at the confinement root: segments above it are not\n"
    "    // places this picker can go, so they aren't rendered at all. The root shows\n"
    "    // as its basename; only the path below it gets '/'-separated segments.\n"
    "    var rootPath = data.root || '/';\n"
    "    var isUrl = rootPath.indexOf('://') !== -1;\n"
    "    h += '<div class=\"tlc-ds-breadcrumb\">';\n"
    "    var rel, base;\n"
    "    if (isUrl) {\n"
    "      h += '<span data-ds-nav=\"' + _esc(rootPath) + '\">' + _esc(_loc.name || rootPath) + '</span>';\n"
    "      rel = data.path.slice(rootPath.length).split('/').filter(Boolean);\n"
    "      base = rootPath;\n"
    "    } else if (rootPath === '/') {\n"
    "      h += '<span data-ds-nav=\"/\">/</span>';\n"
    "      rel = data.path.split('/').filter(Boolean);\n"
    "      base = '';\n"
    "    } else {\n"
    "      var rootLabel = rootPath.split('/').filter(Boolean).pop() || '/';\n"
    "      h += '<span data-ds-nav=\"' + _esc(rootPath) + '\">' + _esc(rootLabel) + '</span>';\n"
    "      rel = data.path.slice(rootPath.length).split('/').filter(Boolean);\n"
    "      base = rootPath;\n"
    "    }\n"
    "    for (var i = 0; i < rel.length; i++) {\n"
    "      h += '<span class=\"sep\">/</span>';\n"
    "      base = base + '/' + rel[i];\n"
    "      h += '<span data-ds-nav=\"' + _esc(base) + '\">' + _esc(rel[i]) + '</span>';\n"
    "    }\n"
    "    // Select-folder button (for mode='folder'). In output mode, a current\n"
    "    // directory that isn't writable can't receive a save, so disable the button.\n"
    "    if (mode === 'folder') {\n"
    "      var folderUnwritable = (purpose === 'output' && data.writable === false);\n"
    "      h += '<button type=\"button\" class=\"ds-select-btn\" data-ds-select-folder=\"' + _esc(data.path) + '\"'\n"
    "         + (folderUnwritable ? ' disabled title=\"Not writable — you may not be able to save here\"' : '')\n"
    "         + ' style=\"margin-left:auto\">Select This Folder</button>';\n"
    "    }\n"
    "    h += '</div>';\n"
    "    // Filter note — only files are glob-filtered server-side (see data_source_routes.py);\n"
    "    // folders always show regardless of the pattern, so this caption is about what's\n"
    "    // selectable here, not what's listed.\n"
    "    if (glob) {\n"
    "      h += '<div class=\"tlc-ds-filter-note\">Showing files matching: ' + _esc(glob) + '</div>';\n"
    "    }\n"
    "    // Entries\n"
    "    if (data.parent != null) {\n"
    "      h += '<div class=\"tlc-ds-entry\" data-ds-nav=\"' + _esc(data.parent) + '\">';\n"
    "      h += '<span class=\"ds-icon\">↑</span>';\n"
    "      h += '<span class=\"ds-name\" style=\"color:var(--text-muted)\">..</span>';\n"
    "      h += '</div>';\n"
    "    }\n"
    "    if (!data.entries || data.entries.length === 0) {\n"
    "      h += '<div class=\"tlc-ds-empty\">Empty directory</div>';\n"
    "    } else {\n"
    "      data.entries.forEach(function(e) {\n"
    "        var isDir = (e.type === 'dir');\n"
    "        // Input mode: a folder the host can't open is a dead end — skip it entirely.\n"
    "        // undefined => accessible (older host without the flag), so only an explicit\n"
    "        // false hides it; files and accessible dirs render as normal.\n"
    "        if (isDir && purpose !== 'output' && e.accessible === false) { return; }\n"
    "        // Output mode: show EVERY folder, but flag one that can't be written to so\n"
    "        // the user still sees it (and can descend to a writable subdir). undefined =>\n"
    "        // writable (older host), so only an explicit false flags it.\n"
    "        var flagged = (isDir && purpose === 'output' && e.writable === false);\n"
    "        h += '<div class=\"tlc-ds-entry' + (flagged ? ' tlc-ds-entry-disabled' : '') + '\"';\n"
    "        if (isDir) {\n"
    "          // Navigable in both modes: a flagged (non-writable) folder stays clickable\n"
    "          // so the user can descend into it to find a writable subdirectory.\n"
    "          h += ' data-ds-nav=\"' + _esc(e.url || (data.path.replace(/\\/$/, '') + '/' + e.name)) + '\"';\n"
    "        }\n"
    "        if (flagged) h += ' title=\"Not writable — you may not be able to save here\"';\n"
    "        h += '>';\n"
    "        var icon = isDir ? (flagged ? '🔒' : '📁') : '📄';\n"
    "        h += '<span class=\"ds-icon\">' + icon + '</span>';\n"
    "        h += '<span class=\"ds-name\">' + _esc(e.name) + (e.type === 'dir' ? '/' : '') + '</span>';\n"
    "        if (e.size != null) h += '<span class=\"ds-size\">' + _fmtSize(e.size) + '</span>';\n"
    "        if (e.type === 'file') {\n"
    "          h += '<button type=\"button\" class=\"ds-select-btn\" data-ds-select=\"'\n"
    "             + _esc(e.url || (data.path.replace(/\\/$/, '') + '/' + e.name)) + '\">Select</button>';\n"
    "        }\n"
    "        h += '</div>';\n"
    "      });\n"
    "    }\n"
    "    if (data.truncated) h += '<div class=\"tlc-ds-filter-note\">More items than shown here.</div>';\n"
    "    panel.innerHTML = h;\n"
    "\n"
    "    // Location change: the run target's disk, or a bucket\n"
    "    var locSel = panel.querySelector('[data-ds-loc]');\n"
    "    if (locSel) locSel.addEventListener('change', function() {\n"
    "      _loc = _list[parseInt(locSel.value, 10)] || _defaultLoc();\n"
    "      _browseTo(_loc.kind === 'bucket' ? _loc.url : _loc.kind === 'node' ? _loc.files_root : '~', true);\n"
    "    });\n"
    "    // Bind navigation clicks\n"
    "    panel.querySelectorAll('[data-ds-nav]').forEach(function(el) {\n"
    "      el.addEventListener('click', function(ev) {\n"
    "        ev.stopPropagation();\n"
    "        _browseTo(el.getAttribute('data-ds-nav'));\n"
    "      });\n"
    "    });\n"
    "    // Bind select buttons (a file) and the select-folder button\n"
    "    panel.querySelectorAll('[data-ds-select],[data-ds-select-folder]').forEach(function(el) {\n"
    "      el.addEventListener('click', function(ev) {\n"
    "        ev.stopPropagation();\n"
    "        _pick(el.getAttribute('data-ds-select') || el.getAttribute('data-ds-select-folder'), _loc);\n"
    "      });\n"
    "    });\n"
    "  }\n"
    "\n"
    "  // A picked value remembers where it was picked, so a later change of run target can say that the new\n"
    "  // target cannot read it. Typing over it forgets that.\n"
    "  function _pick(value, loc) {\n"
    "    input.value = value;\n"
    "    input.dataset.dsPicked = value;\n"
    "    input.dataset.dsWhere = loc.kind === 'node' ? 'node:' + loc.node_id : loc.kind;\n"
    "    input.dataset.dsWhereLabel = loc.kind === 'node' ? loc.name : (loc.kind === 'local' ? "
    "_hostLabel(_tlcRunTarget()) : '');\n"
    "    _panelOpen = false;\n"
    "    panel.classList.remove('open');\n"
    "    input.dispatchEvent(new Event('input', {bubbles: true}));\n"
    "    input.dispatchEvent(new Event('change', {bubbles: true}));\n"
    "  }\n"
    "\n"
    "  // The value against the run target: a note when the target cannot reach it (see _tlcDsReachNote).\n"
    "  // A typed path on a node run is checked on the node (the host's path-check), once per path.\n"
    "  var _checks = {};\n"
    "  var _reviewSeq = 0;\n"
    "  function _pathCheck(nodeId, path) {\n"
    "    var key = nodeId + '|' + path;\n"
    "    if (!_checks[key]) {\n"
    "      _checks[key] = API.authFetch(computeUrl + '/api/infra/nodes/' + encodeURIComponent(nodeId) + "
    "'/path-check?path='\n"
    "        + encodeURIComponent(path))\n"
    "        .then(function(r) { return r.ok ? r.json() : null; })\n"
    "        .catch(function() { delete _checks[key]; return null; });\n"
    "    }\n"
    "    return _checks[key];\n"
    "  }\n"
    "  function _review() {\n"
    "    if (!reachEl) return;\n"
    "    var seq = ++_reviewSeq;\n"
    "    var t = _tlcRunTarget();\n"
    "    var value = input.value.trim();\n"
    "    if (!value || !t) { reachEl.textContent = ''; reachEl.style.display = 'none'; return; }\n"
    "    var where = input.dataset.dsPicked === value ? (input.dataset.dsWhere || '') : '';\n"
    "    var ctx = { target: t, where: where, whereLabel: where ? (input.dataset.dsWhereLabel || '') : '',\n"
    "                hostLabel: _hostLabel(t), nodeLabel: '', probe: null, check: null };\n"
    "    var nodeId = t.target === 'node' ? t.node_id : '';\n"
    "    _nodeInfo(nodeId).then(function(info) {\n"
    "      ctx.nodeLabel = t.label || (info && info.label) || nodeId;\n"
    "      if (!nodeId) return null;\n"
    "      if (value.indexOf('://') !== -1) { ctx.probe = _tlcDsBucketReach(value, info && info.storage); return null; "
    "}\n"
    "      var typed = !where && purpose !== 'output' && /^[/~]/.test(value);\n"
    "      return typed ? _pathCheck(nodeId, value) : null;\n"
    "    }).then(function(check) {\n"
    "      if (seq !== _reviewSeq) return;\n"
    "      ctx.check = check;\n"
    "      var note = _tlcDsReachNote(value, ctx);\n"
    "      reachEl.textContent = note;\n"
    "      reachEl.style.display = note ? '' : 'none';\n"
    "    });\n"
    "  }\n"
    "  input.addEventListener('change', _review);\n"
    "  input.addEventListener('input', function() {\n"
    "    if (input.value.trim() !== input.dataset.dsPicked && reachEl) reachEl.style.display = 'none';\n"
    "  });\n"
    "\n"
    "  // The run target decides what can be offered: no upload to a node (an upload lands on the compute host).\n"
    "  function _applyTarget() {\n"
    "    var t = _tlcRunTarget();\n"
    "    var onNode = !!(t && t.target === 'node');\n"
    "    if (uploadBtn) uploadBtn.style.display = onNode ? 'none' : '';\n"
    "    if (onNode && uploadZone) uploadZone.classList.remove('open');\n"
    "  }\n"
    "  _applyTarget();\n"
    "  if (API && typeof API.onRunTargetChange === 'function') {\n"
    "    API.onRunTargetChange(function() {\n"
    "      if (input.isConnected === false) return;  // a re-rendered form left this one behind\n"
    "      _applyTarget();\n"
    "      _review();\n"
    "      if (_panelOpen) _open();  // the open panel follows the new target\n"
    "    });\n"
    "  }\n"
    "  _review();\n"
    "\n"
    "  // Upload zone\n"
    "  if (uploadBtn && uploadZone) {\n"
    "    var fileInput = document.getElementById(idPrefix + '-ds-file-input');\n"
    "    var uploadInfo = document.getElementById(idPrefix + '-ds-upload-info');\n"
    "\n"
    "    uploadBtn.addEventListener('click', function() {\n"
    "      var isOpen = uploadZone.classList.toggle('open');\n"
    "      if (isOpen) { panel.classList.remove('open'); _panelOpen = false; }\n"
    "    });\n"
    "\n"
    "    uploadZone.addEventListener('click', function() { fileInput.click(); });\n"
    "    uploadZone.addEventListener('dragover', function(ev) {\n"
    "      ev.preventDefault(); uploadZone.classList.add('dragging');\n"
    "    });\n"
    "    uploadZone.addEventListener('dragleave', function() {\n"
    "      uploadZone.classList.remove('dragging');\n"
    "    });\n"
    "    uploadZone.addEventListener('drop', function(ev) {\n"
    "      ev.preventDefault(); uploadZone.classList.remove('dragging');\n"
    "      if (ev.dataTransfer.files.length > 0) _uploadFile(ev.dataTransfer.files[0]);\n"
    "    });\n"
    "    fileInput.addEventListener('change', function() {\n"
    "      if (fileInput.files.length > 0) _uploadFile(fileInput.files[0]);\n"
    "    });\n"
    "\n"
    "    function _uploadFile(file) {\n"
    "      uploadInfo.style.display = '';\n"
    "      uploadInfo.textContent = 'Uploading ' + file.name + '…';\n"
    "      uploadZone.style.opacity = '0.6';\n"
    "      uploadZone.style.pointerEvents = 'none';\n"
    "\n"
    "      var formData = new FormData();\n"
    "      formData.append('data', file);\n"
    "\n"
    "      API.authFetch(computeUrl + '/api/plugins/' + pluginId + '/upload-temp', {\n"
    "        method: 'POST',\n"
    "        body: formData,\n"
    "      })\n"
    "      .then(function(r) { return r.json(); })\n"
    "      .then(function(result) {\n"
    "        input.value = result.path;\n"
    "        // An upload lands on the compute host's disk.\n"
    "        input.dataset.dsPicked = result.path;\n"
    "        input.dataset.dsWhere = 'local';\n"
    "        input.dataset.dsWhereLabel = _hostLabel(_tlcRunTarget());\n"
    "        uploadInfo.innerHTML = '<span style=\"color:var(--success)\">✓</span> '\n"
    "          + _esc(file.name) + ' <span style=\"color:var(--text-muted)\">→ '\n"
    "          + _esc(result.path) + '</span>';\n"
    "        uploadZone.classList.remove('open');\n"
    "        input.dispatchEvent(new Event('input', {bubbles: true}));\n"
    "        input.dispatchEvent(new Event('change', {bubbles: true}));\n"
    "      })\n"
    "      .catch(function(err) {\n"
    "        uploadInfo.innerHTML = '<span style=\"color:var(--error)\">Upload failed:</span> '\n"
    "          + _esc(String(err));\n"
    "      })\n"
    "      .finally(function() {\n"
    "        uploadZone.style.opacity = '';\n"
    "        uploadZone.style.pointerEvents = '';\n"
    "      });\n"
    "    }\n"
    "  }\n"
    "\n"
    "  // Close panel on outside click\n"
    "  document.addEventListener('click', function(ev) {\n"
    "    if (!_panelOpen) return;\n"
    "    var wrapper = input.closest('.tlc-ds-wrapper');\n"
    "    if (wrapper && !wrapper.contains(ev.target)) {\n"
    "      _panelOpen = false;\n"
    "      panel.classList.remove('open');\n"
    "      if (uploadZone) uploadZone.classList.remove('open');\n"
    "    }\n"
    "  });\n"
    "}\n"
    "\n"
    "function _tlcGetDataSourceValue(idPrefix) {\n"
    "  var el = document.getElementById(idPrefix);\n"
    "  return el ? el.value.trim() : '';\n"
    "}\n"
    "\n"
    "function _tlcSetDataSourceValue(idPrefix, value) {\n"
    "  var el = document.getElementById(idPrefix);\n"
    "  if (el) {\n"
    "    el.value = value || '';\n"
    "    el.dispatchEvent(new Event('input', {bubbles: true}));\n"
    "    el.dispatchEvent(new Event('change', {bubbles: true}));\n"
    "  }\n"
    "}\n"
)
# fmt: on


def data_source_ui_script() -> str:
    """Return the shared data-source UI JavaScript block."""
    return DATA_SOURCE_UI_JS
